### ISSUE TITLE
Segmentation Fault while viewing IP Address

### ISSUE THREAD

**Issue by melvinabraham** [sachinkamath/project-2ndsem#3]
While viewing the IP Address either as a Guest or as a User there is a Core Dump due to Segmentation Fault. Issue needs to be addressed.

**Comment by sachinkamath** [comment]
Works for me :/ Can you tell me your GCC version?

**Comment by melvinabraham** [comment]
GCC Version 4.8.2 . on Ubuntu 14.04.

**Comment by sachinkamath** [comment]
Well, I am using a later version of it and it seems to be working fine. My compiler is probably drunk :P 

Send a PR if you manage to find a workaround.

**Comment by sachinkamath** [comment]
Closing this. :dancer:
